import { Artwork } from "./types";

// Demo mode kicks in automatically whenever there's no real Supabase project
// configured yet (i.e. you haven't filled in .env.local). This lets you run
// `npm run dev` immediately and see the site with sample artwork, before
// setting up any real accounts.
export const isDemoMode = !process.env.NEXT_PUBLIC_SUPABASE_URL;

export const DEMO_ARTWORKS: Artwork[] = [
  {
    id: "demo-1",
    title: "Low Tide, Late Afternoon",
    slug: "low-tide-late-afternoon",
    description:
      "An oil study of the coastline at low tide, painted over three sessions as the light shifted from gold to grey.",
    medium: "Oil on canvas",
    dimensions: "24 x 30 in",
    price_cents: 68000,
    is_print: false,
    quantity_available: 1,
    image_urls: ["https://picsum.photos/seed/artwork1/900/1125"],
    status: "available",
    catalogue_number: 1,
    edition: null,
    signed: true,
    marked_new_at: null,
    home_slide: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-2",
    title: "Interior with Yellow Chair",
    slug: "interior-with-yellow-chair",
    description:
      "A quiet domestic scene, built up in thin glazes of acrylic over several weeks.",
    medium: "Acrylic on panel",
    dimensions: "18 x 24 in",
    price_cents: 42000,
    is_print: false,
    quantity_available: 1,
    image_urls: ["https://picsum.photos/seed/artwork2/900/1125"],
    status: "available",
    catalogue_number: 2,
    edition: null,
    signed: true,
    marked_new_at: null,
    home_slide: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-3",
    title: "Orchard Study No. 4",
    slug: "orchard-study-no-4",
    description:
      "Part of an ongoing series of small studies made on-site in the same orchard across a single season.",
    medium: "Watercolor on paper",
    dimensions: "9 x 12 in",
    price_cents: 21000,
    is_print: false,
    quantity_available: 1,
    image_urls: ["https://picsum.photos/seed/artwork3/900/1125"],
    status: "sold_out",
    catalogue_number: 3,
    edition: null,
    signed: true,
    marked_new_at: null,
    home_slide: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-4",
    title: "Harbor Lights, Print Edition",
    slug: "harbor-lights-print-edition",
    description:
      "A giclee print of the original oil painting, printed on archival cotton rag paper. Edition of 50.",
    medium: "Giclee print",
    dimensions: "16 x 20 in",
    price_cents: 12000,
    is_print: true,
    quantity_available: 12,
    image_urls: ["https://picsum.photos/seed/artwork4/900/1125"],
    status: "available",
    catalogue_number: 4,
    edition: "Edition of 50",
    signed: true,
    marked_new_at: null,
    home_slide: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-5",
    title: "Portrait Commission",
    slug: "portrait-commission",
    description:
      "Custom portrait work in oil, painted from reference photos. Reach out to discuss size, timeline, and pricing for your piece.",
    medium: "Oil on canvas",
    dimensions: "Custom sizing available",
    price_cents: 0,
    is_print: false,
    quantity_available: 0,
    image_urls: ["https://picsum.photos/seed/artwork5/900/1125"],
    status: "inquire_only",
    catalogue_number: 5,
    edition: null,
    signed: true,
    marked_new_at: null,
    home_slide: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-6",
    title: "Winter Field, Dusk",
    slug: "winter-field-dusk",
    description:
      "Painted from memory the week after a January storm, working quickly to hold onto the color of the light.",
    medium: "Oil on canvas",
    dimensions: "30 x 40 in",
    price_cents: 95000,
    is_print: false,
    quantity_available: 1,
    image_urls: ["https://picsum.photos/seed/artwork6/900/1125"],
    status: "available",
    catalogue_number: 6,
    edition: null,
    signed: true,
    marked_new_at: null,
    home_slide: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
